- hosts: all

  vars_files:
    - vars/main.yml

  become: true

  pre_tasks:
  - name: create install check directory
    file: path="{{ check_dir }}" state=directory
  - name: Install packages
    apt: name={{item}} update_cache=yes
    with_items:
      - python3-pip
      - python3-mysqldb

  roles:
    - common-setup
    - geerlingguy.mysql
    - bennojoy.openldap_server
    - wildfly
    - keycloak
    - keycloak_wf9_adapter
    - serenity-db
    - ldap-data
    - keycloak-realm
    - jdauphant.ssl-certs
    - jdauphant.nginx
